language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
# command to install dependencies
install:
  - "pip install ."
  - "pip install -r requirements.txt"
  - "pip install pytest-cov coveralls"
# command to run tests
script: py.test -v --cov homeslice
after_success: coveralls
